codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%

    patch:
      default:
        target: 85%
        threshold: 0%
        base: auto
        branches:
          - main
          - digilocker_heroku
          - dev-2
        if_ci_failed: ignore
        only_pulls: true

comment:
  layout: "diff, files"
  require_changes: true

ignore: []
