version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./main.py:/app/main.py
    depends_on:
      - redis

  redis:
    image: "redis:alpine"